ALL_POSSIBLE_SYMPTOMS = [
    "itching", "skin_rash", "nodal_skin_eruptions", "continuous_sneezing", "shivering", "chills",
    "joint_pain", "stomach_pain", "acidity", "ulcers_on_tongue", "muscle_wasting", "vomiting",
    "burning_micturition", "spotting_ urination", "fatigue", "weight_gain", "anxiety",
    "cold_hands_and_feets", "mood_swings", "weight_loss", "restlessness", "lethargy",
    "patches_in_throat", "irregular_sugar_level", "cough", "high_fever", "sunken_eyes",
    "breathlessness", "sweating", "dehydration", "indigestion", "headache", "yellowish_skin",
    "dark_urine", "nausea", "loss_of_appetite", "pain_behind_the_eyes", "back_pain", "constipation",
    "abdominal_pain", "diarrhoea", "mild_fever", "yellow_urine", "yellowing_of_eyes",
    "acute_liver_failure", "fluid_overload", "swelling_of_stomach", "swelled_lymph_nodes", "malaise",
    "blurred_and_distorted_vision", "phlegm", "throat_irritation", "redness_of_eyes", "sinus_pressure",
    "runny_nose", "congestion", "chest_pain", "weakness_in_limbs", "fast_heart_rate",
    "pain_during_bowel_movements", "pain_in_anal_region", "bloody_stool", "irritation_in_anus",
    "neck_pain", "dizziness", "cramps", "bruising", "obesity", "swollen_legs", "swollen_blood_vessels",
    "puffy_face_and_eyes", "enlarged_thyroid", "brittle_nails", "swollen_extremeties", "excessive_hunger",
    "extra_marital_contacts", "drying_and_tingling_lips", "slurred_speech", "knee_pain",
    "hip_joint_pain", "muscle_weakness", "stiff_neck", "swelling_joints", "movement_stiffness",
    "spinning_movements", "loss_of_balance", "unsteadiness", "weakness_of_one_body_side",
    "loss_of_smell", "bladder_discomfort", "foul_smell_of urine", "continuous_feel_of_urine",
    "passage_of_gases", "internal_itching", "toxic_look_(typhos)", "depression", "irritability",
    "muscle_pain", "altered_sensorium", "red_spots_over_body", "belly_pain", "abnormal_menstruation",
    "dischromic _patches", "watering_from_eyes", "increased_appetite", "polyuria", "family_history",
    "mucoid_sputum", "rusty_sputum", "lack_of_concentration", "visual_disturbances",
    "receiving_blood_transfusion", "receiving_unsterile_injections", "coma", "stomach_bleeding",
    "distention_of_abdomen", "history_of_alcohol_consumption", "fluid_overload.1", "blood_in_sputum",
    "prominent_veins_on_calf", "palpitations", "painful_walking", "pus_filled_pimples", "blackheads",
    "scurring", "skin_peeling", "silver_like_dusting", "small_dents_in_nails", "inflammatory_nails",
    "blister", "red_sore_around_nose", "yellow_crust_ooze"
]

ALL_POSSIBLE_SYMPTOMS_PT_BR = {
    "itching": "coceira",
    "skin_rash": "erupção cutânea",
    "nodal_skin_eruptions": "erupções cutâneas nodais",
    "continuous_sneezing": "espirros contínuos",
    "shivering": "arrepios",
    "chills": "calafrios",
    "joint_pain": "dor nas articulações",
    "stomach_pain": "dor de estômago",
    "acidity": "acidez",
    "ulcers_on_tongue": "úlceras na língua",
    "muscle_wasting": "perda de massa muscular",
    "vomiting": "vômitos",
    "burning_micturition": "micção ardente",
    "spotting_ urination": "micção com pontos",
    "fatigue": "fadiga",
    "weight_gain": "ganho de peso",
    "anxiety": "ansiedade",
    "cold_hands_and_feets": "mãos e pés frios",
    "mood_swings": "oscilações de humor",
    "weight_loss": "perda de peso",
    "restlessness": "inquietação",
    "lethargy": "letargia",
    "patches_in_throat": "manchas na garganta",
    "irregular_sugar_level": "nível irregular de açúcar",
    "cough": "tosse",
    "high_fever": "febre alta",
    "sunken_eyes": "olhos afundados",
    "breathlessness": "falta de ar",
    "sweating": "suor",
    "dehydration": "desidratação",
    "indigestion": "indigestão",
    "headache": "dor de cabeça",
    "yellowish_skin": "pele amarelada",
    "dark_urine": "urina escura",
    "nausea": "náusea",
    "loss_of_appetite": "perda de apetite",
    "pain_behind_the_eyes": "dor nos olhos",
    "back_pain": "dor nas costas",
    "constipation": "constipação",
    "abdominal_pain": "dor abdominal",
    "diarrhoea": "diarreia",
    "mild_fever": "febre leve",
    "yellow_urine": "urina amarela",
    "yellowing_of_eyes": "amarelamento dos olhos",
    "acute_liver_failure": "insuficiência hepática aguda",
    "fluid_overload": "sobrecarga de fluido",
    "swelling_of_stomach": "inchaço do estômago",
    "swelled_lymph_nodes": "linfonodos inchados",
    "malaise": "mal-estar",
    "blurred_and_distorted_vision": "visão turva e distorcida",
    "phlegm": "catarro",
    "throat_irritation": "irritação na garganta",
    "redness_of_eyes": "vermelhidão nos olhos",
    "sinus_pressure": "pressão nos seios da face",
    "runny_nose": "nariz escorrendo",
    "congestion": "congestão",
    "chest_pain": "dor no peito",
    "weakness_in_limbs": "fraqueza nos membros",
    "fast_heart_rate": "ritmo cardíaco acelerado",
    "pain_during_bowel_movements": "dor durante movimentos intestinais",
    "pain_in_anal_region": "dor na região anal",
    "bloody_stool": "fezes com sangue",
    "irritation_in_anus": "irritação no ânus",
    "neck_pain": "dor no pescoço",
    "dizziness": "tontura",
    "cramps": "câimbras",
    "bruising": "hematomas",
    "obesity": "obesidade",
    "swollen_legs": "pernas inchadas",
    "swollen_blood_vessels": "vasos sanguíneos inchados",
    "puffy_face_and_eyes": "rosto e olhos inchados",
    "enlarged_thyroid": "tireoide aumentada",
    "brittle_nails": "unhas quebradiças",
    "swollen_extremeties": "extremidades inchadas",
    "excessive_hunger": "fome excessiva",
    "extra_marital_contacts": "contatos extraconjugais",
    "drying_and_tingling_lips": "lábios secos e formigamento",
    "slurred_speech": "fala arrastada",
    "knee_pain": "dor no joelho",
    "hip_joint_pain": "dor na articulação do quadril",
    "muscle_weakness": "fraqueza muscular",
    "stiff_neck": "pescoço rígido",
    "swelling_joints": "articulações inchadas",
    "movement_stiffness": "rigidez nos movimentos",
    "spinning_movements": "movimentos giratórios",
    "loss_of_balance": "perda de equilíbrio",
    "unsteadiness": "instabilidade",
    "weakness_of_one_body_side": "fraqueza de um lado do corpo",
    "loss_of_smell": "perda do olfato",
    "bladder_discomfort": "desconforto na bexiga",
    "foul_smell_of urine": "cheiro desagradável da urina",
    "continuous_feel_of_urine": "sensação contínua de urina",
    "passage_of_gases": "passagem de gases",
    "internal_itching": "coceira interna",
    "toxic_look_(typhos)": "aparência tóxica (tifos)",
    "depression": "depressão",
    "irritability": "irritabilidade",
    "muscle_pain": "dor muscular",
    "altered_sensorium": "sensorium alterado",
    "red_spots_over_body": "manchas vermelhas pelo corpo",
    "belly_pain": "dor abdominal",
    "abnormal_menstruation": "menstruação anormal",
    "dischromic _patches": "manchas descoloridas",
    "watering_from_eyes": "lacrimação dos olhos",
    "increased_appetite": "aumento do apetite",
    "polyuria": "poliúria",
    "family_history": "histórico familiar",
    "mucoid_sputum": "escarro mucoso",
    "rusty_sputum": "escarro enferrujado",
    "lack_of_concentration": "falta de concentração",
    "visual_disturbances": "distúrbios visuais",
    "receiving_blood_transfusion": "recebimento de transfusão de sangue",
    "receiving_unsterile_injections": "recebimento de injeções não estéreis",
    "coma": "coma",
    "stomach_bleeding": "sangramento no estômago",
    "distention_of_abdomen": "distensão do abdômen",
    "history_of_alcohol_consumption": "histórico de consumo de álcool",
    "fluid_overload.1": "sobrecarga de fluido",
    "blood_in_sputum": "sangue no escarro",
    "prominent_veins_on_calf": "veias proeminentes na panturrilha",
    "palpitations": "palpitações",
    "painful_walking": "caminhada dolorosa",
    "pus_filled_pimples": "espinhas cheias de pus",
    "blackheads": "cravos",
    "scurring": "escamação",
    "skin_peeling": "descamação da pele",
    "silver_like_dusting": "poeira prateada",
    "small_dents_in_nails": "pequenas depressões nas unhas",
    "inflammatory_nails": "unhas inflamadas",
    "blister": "bolha",
    "red_sore_around_nose": "ferida vermelha ao redor do nariz",
    "yellow_crust_ooze": "secreção de crosta amarela"
}